**NumPy stands for Numerical Python.**

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

In [ ]:
pip install numpy
import numpy as np

In [ ]:
#1-d Array
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
#2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr2.ndim)

2


In [ ]:
arr3=np.zeros((2,3))

In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
print(arr3.ndim)

2


In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
arr4=np.ones((3,3))

In [ ]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [ ]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])

print(arr1[0])

1


In [ ]:
arr1[3]

4

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
#2nd element on 1st row
arr2[0,1]

2

In [ ]:
arr2[1]