In [2]:
# Array Split
import numpy as np
arr= np.array([1,2,3,4,5,6])
new_arr= np.array_split(arr,2)
print(new_arr)

[array([1, 2, 3]), array([4, 5, 6])]


In [3]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
new_arr= np.array_split(arr,3)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
new_arr= np.array_split(arr,4)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [5]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [6]:
# Searching Arrays

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [10]:
# Sorting methods

In [11]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [12]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [13]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [14]:
# Random Numbers in Numpy

In [15]:
from numpy import random

x = random.randint(100)

print(x)

51


In [17]:
#Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.4908321243589523


In [18]:
#Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

[87 66 31 95 41]


In [19]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.32257621 0.28338052 0.33607766 0.31794257 0.62139103]
 [0.6971956  0.1770368  0.15998536 0.67135779 0.74674744]
 [0.39759801 0.8544103  0.14344365 0.35809775 0.24541111]]


In [25]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 7 9 9]
 [5 7 3 5 3]
 [3 7 5 3 5]]


In [27]:
#Random Distribution
#A random distribution is a set of random numbers that follow a certain probability density function.

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 7 7 7 7 7 7 7 7 5 5 5 7 5 7 7 7 3 5 7 5 7 5 5 7 3 3 5 7 7 5 7 3 5 5 7
 5 5 5 7 7 3 3 7 7 7 7 5 7 3 5 7 7 7 7 7 7 7 7 3 7 3 5 5 7 7 3 3 7 3 3 7 7
 5 5 7 7 7 7 5 5 5 7 7 5 7 5 3 5 7 5 5 7 7 3 5 5 7 5]
